import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import {Button, CardGroup, Card,} from 'react-bootstrap';
import Carousel from 'react-bootstrap/Carousel';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CarBikes360</title>
        <meta name="description"content="Generated by create next app" />
        <link rel="icon" href="/logo2.jpg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.carbike360.com/">CarBikes360</a>
        </h1>

        <p className={styles.description}>
        <b>Details About The Bikes</b>
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
            <h2>Available Bikes </h2>
          <div className={styles.card}>
            <div className={styles}>
              <Image className={styles.image} src="/01.jpg" alt="pic1" width="250px" height="200px"/>
              <h4>KTM</h4>
              <h4>₹ 1.76 lakh onwards</h4>
              <h4><button type="button">View Details</button></h4>

            </div>
            <div>
            <Image className={styles.image} src="/02.jpg" width="250px" height="200px"/>
            <h4>Yamaha R15</h4>
            <h4>₹ 1.15 Lakh onwards</h4>
           <h4> <button type="button">View Details</button></h4>

            </div>
            <div>
            <Image className={styles.image} src="/03.jpg" width="250px" height="200px"/>
            <h4>TVS Apache</h4>
            <h4>₹ 1.05 lakh onwards</h4>
            <h4><button type="button">View Details</button></h4>
            </div>
            <div>
            <Image className={styles.image} src="/04.jpg" width="250px" height="200px"/>
            <h4>Yamaha FZ</h4>
            <h4>₹ 1.16 lakh onwards</h4>
            <h4><button type="button">View Details</button></h4>

            </div>
          </div>
         
        </div>
      </main>
      <CardGroup>
      <Card>
        <Card.Img variant="top" src="/05.jpg" width="250" height="200" />
        <Card.Body>
          <Card.Title>Kawasaki Ninja</Card.Title>
          <Card.Text>
           This Bike is amazing
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/06.jpg" width="250" height="200" />
        <Card.Body>
          <Card.Title>Ducati</Card.Title>
          <Card.Text>
            This Bike is amazing
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/07.jpg" width="250" height="200" />
        <Card.Body>
          <Card.Title>Hero Karizma</Card.Title>
          <Card.Text>
            This Car is amazing
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
    </CardGroup>
      <footer className={styles.footer}>
        <a
          href="https://www.carbike360.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{''}
          <span className={styles.logo}>
            <Image src="/CarBike.webp" alt="logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}