import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import {Button, CardGroup, Card,} from 'react-bootstrap';
import Carousel from 'react-bootstrap/Carousel';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CarBikes360</title>
        <meta name="description"content="Generated by create next app" />
        <link rel="icon" href="/logo2.jpg" />
      </Head>
      <Carousel>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="s1.jpg" width="500px" height="300px"          
          alt="First slide"
        />
        <Carousel.Caption>
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="s2.jpg" width="500px" height="300px"
          alt="Second slide"
        />

        <Carousel.Caption>
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
        <img
          className="d-block w-100"
          src="s3.jpg" width="500px" height="300px"
          alt="Third slide"
        />

        <Carousel.Caption>
          <h3>Third slide label</h3>
          <p>
            Praesent commodo cursus magna, vel scelerisque nisl consectetur.
          </p>
        </Carousel.Caption>
      </Carousel.Item>
    </Carousel>
   
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.carbike360.com/">CarBikes360</a>
        </h1>

        <p className={styles.description}>
        <b>Details About The Cars</b>
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
            <h2>Available Cars </h2>
          <div className={styles.card}>
            <div className={styles}>
              <Image className={styles.image} src="/1.jpg" alt="pic1" width="250px" height="200px"/>
              <h4>Honda City</h4>
              <h4>₹ 15.55 lakh onwards</h4>
              <h4><button type="button">View Details</button></h4>
            
             </div>
            <div>
            <Image className={styles.image} src="/2.jpg" width="250px" height="200px"/>
            <h4>BMW</h4>
            <h4>₹ 46.86 Lakh onwards</h4>
           <h4> <button type="button">View Details</button></h4>

            </div>
            <div>
            <Image className={styles.image} src="/3.jpg" width="250px" height="200px"/>
            <h4>Maruti Vitara Brezza</h4>
            <h4>₹ 13.96 lakh onwards</h4>
            <h4><button type="button">View Details</button></h4>

            </div>
            <div>
            <Image className={styles.image} src="/4.jpg" width="250px" height="200px"/>
            <h4>KIA</h4>
            <h4>₹ 20.75 lakh onwards</h4>
            <h4><button type="button">View Details</button></h4>

           

            </div>
          </div>
         
        </div>
      </main>
      <CardGroup>
      <Card>
        <Card.Img variant="top" src="/5.jpg" width="250" height="250" />
        <Card.Body>
          <Card.Title>Mercedes</Card.Title>
          <Card.Text>
           This Car is amazing
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/6.jpg" width="250" height="250" />
        <Card.Body>
          <Card.Title>Audi</Card.Title>
          <Card.Text>
            This Car is amazing
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
      <Card>
        <Card.Img variant="top" src="/7.jpg" width="250" height="250" />
        <Card.Body>
          <Card.Title>Ferrari</Card.Title>
          <Card.Text>
            This Car is amazing
            <h4><a href="/cars/index2" >Bike page</a></h4>
          
          </Card.Text>
        </Card.Body>
        <Card.Footer>
          <small className="text-muted">Last updated 3 mins ago</small>
        </Card.Footer>
      </Card>
    </CardGroup>
    
      <footer className={styles.footer}>
        <a
          href="https://www.carbike360.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{''}
          <span className={styles.logo}>
            <Image src="/CarBike.webp" alt="logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}